/**
 * dataClient.js — the ONLY module in the frontend that knows the file paths
 * and fetch/cache strategy for content data (problems.json, oc.json, notes).
 *
 * Everything else (lib/problems.filter.js, problem.service.js,
 * notes.service.js, roadmap.service.js, every hook/page) calls only the
 * public methods below. This is deliberate — see docs/03-DATA-LAYER.md and
 * docs/11-FUTURE-ROADMAP.md: when the 10-file data split ships, only this
 * file's internals change.
 *
 * Public API:
 *   getProblems()          -> Promise<Problem[]>
 *   getProblemDetail(id)   -> Promise<Problem & OcFields>
 *   getNotesIndex()        -> Promise<NotesIndex>
 *   getNote(slug)          -> Promise<Note|null>
 *
 * All four are safe to call repeatedly / concurrently from multiple
 * components — in-flight requests are de-duplicated, results are cached
 * in-memory for the session and mirrored into IndexedDB across sessions.
 */

import { idbCache } from './idbCache.js';
import { mergeOcRecord } from './ocMerge.js';
import { NOTES_TOPICS_INDEX } from '../../constants/notes.js';

const PATHS = {
  PROBLEMS: '/data/explained/problems.json',
  OC: '/data/explained/oc.json',
  NOTES_DIR: '/data/notes',
};

// Build-time enumeration of which note JSON files actually exist under
// public/data/notes/ — replaces the old runtime manifest.json (previously
// generated by the now-removed scripts/generate-notes-manifest.js) with a
// compile-time glob. Vite's import.meta.glob statically scans the folder
// when the app is built/started, so this is always in sync with whatever
// files are actually on disk — no separate script to remember to run after
// copying data in. Only the keys (paths) are used below; the files
// themselves are still lazy-fetched on demand in getNote().
const noteModules = import.meta.glob('/public/data/notes/*.json');
const AVAILABLE_NOTE_SLUGS = new Set(
  Object.keys(noteModules).map((p) => p.match(/([^/]+)\.json$/)[1])
);

const IDB_KEYS = {
  PROBLEMS: 'content:problems',
  OC: 'content:oc',
};

// Bounded revalidation window — see docs/03-DATA-LAYER.md "Cache freshness".
// A cached copy is used immediately; if it's older than this, a background
// refetch is kicked off (but never hot-swapped mid-session).
const REVALIDATE_AFTER_MS = 60 * 60 * 1000; // 1 hour

// ---- in-memory singleton state -------------------------------------------

let problemsArray = null; // Problem[] once loaded
let problemsInFlight = null; // Promise<Problem[]> while loading
let problemsLoadedAt = 0;

let ocMap = null; // Map<canonical_id, OcRecord> once loaded
let ocInFlight = null;

let notesIndexCache = null;

const noteCache = new Map(); // slug -> Note
const noteInFlight = new Map(); // slug -> Promise<Note>

const detailCache = new Map(); // canonical_id -> merged detail record

// ---- worker plumbing -------------------------------------------------------

let worker = null;
let nextRequestId = 1;
const pendingWorkerRequests = new Map(); // requestId -> {resolve, reject}

function getWorker() {
  if (worker) return worker;

  if (typeof Worker === 'undefined') {
    // Environments without Worker support (very old browsers, some test
    // runners) fall back to main-thread fetch+parse below.
    return null;
  }

  worker = new Worker(new URL('./dataWorker.js', import.meta.url), { type: 'module' });
  worker.onmessage = (event) => {
    const { requestId, ok, records, error } = event.data;
    const pending = pendingWorkerRequests.get(requestId);
    if (!pending) return;
    pendingWorkerRequests.delete(requestId);
    if (ok) pending.resolve(records);
    else pending.reject(new Error(error));
  };
  worker.onerror = (err) => {
    console.error('[dataClient] worker error', err);
  };

  return worker;
}

/** Fetch + parse an NDJSON file, off the main thread when possible. */
async function fetchNdjson(url, kind) {
  const w = getWorker();

  if (w) {
    const requestId = nextRequestId++;
    return new Promise((resolve, reject) => {
      pendingWorkerRequests.set(requestId, { resolve, reject });
      w.postMessage({ requestId, url, kind });
    });
  }

  // Fallback: main-thread fetch + parse (no Worker support).
  const res = await fetch(url);
  if (!res.ok) throw new Error(`Failed to fetch ${url}: ${res.status}`);
  const text = await res.text();
  const out = [];
  for (const line of text.split('\n')) {
    const trimmed = line.trim();
    if (!trimmed) continue;
    try { out.push(JSON.parse(trimmed)); } catch { /* skip malformed line */ }
  }
  return out;
}

// ---- resume-on-foreground handling (mobile hardening, see docs/07) --------
// If a fetch is in-flight when the tab is backgrounded and stalls, retry it
// once the tab is foregrounded again rather than leaving the app stuck.

let staleInFlightFlag = { problems: false, oc: false };

if (typeof document !== 'undefined') {
  const handleResume = () => {
    if (document.visibilityState !== 'visible') return;
    if (staleInFlightFlag.problems && problemsInFlight) {
      // no-op: the same in-flight promise is still being awaited by callers.
      // This handler exists primarily so a *future* stalled-detection layer
      // (e.g. a timeout race) has a clear hook point. Kept intentionally
      // simple here: worker-based fetches don't hang silently the way a
      // suspended main-thread fetch can, but this listener is the agreed
      // safety net per docs/07-MOBILE-CONSIDERATIONS.md.
    }
  };
  document.addEventListener('visibilitychange', handleResume);
  window.addEventListener('pageshow', handleResume);
}

// ---- problems.json ----------------------------------------------------------

async function loadProblemsFromNetwork() {
  const records = await fetchNdjson(PATHS.PROBLEMS, 'problems');
  problemsArray = records;
  problemsLoadedAt = Date.now();
  idbCache.set(IDB_KEYS.PROBLEMS, { records, cachedAt: problemsLoadedAt }).catch(() => {});
  return records;
}

function revalidateProblemsInBackground() {
  loadProblemsFromNetwork().catch((err) => {
    console.warn('[dataClient] background revalidation of problems.json failed', err);
  });
}

export async function getProblems() {
  if (problemsArray) return problemsArray;
  if (problemsInFlight) return problemsInFlight;

  problemsInFlight = (async () => {
    staleInFlightFlag.problems = true;
    try {
      const cached = await idbCache.get(IDB_KEYS.PROBLEMS);
      if (cached && Array.isArray(cached.records)) {
        problemsArray = cached.records;
        problemsLoadedAt = cached.cachedAt || 0;

        if (Date.now() - problemsLoadedAt > REVALIDATE_AFTER_MS) {
          revalidateProblemsInBackground();
        }

        return problemsArray;
      }

      return await loadProblemsFromNetwork();
    } finally {
      staleInFlightFlag.problems = false;
      problemsInFlight = null;
    }
  })();

  return problemsInFlight;
}

// ---- oc.json (lazy, only for should_generate:true detail views) -----------

async function loadOcFromNetwork() {
  const records = await fetchNdjson(PATHS.OC, 'oc');
  const map = new Map(records.map((r) => [r.canonical_id, r]));
  ocMap = map;
  // Storing the raw array (not the Map) in IndexedDB — Maps aren't
  // structured-clone-friendly across all IDB implementations reliably as
  // values without extra care, arrays are safest.
  idbCache.set(IDB_KEYS.OC, { records, cachedAt: Date.now() }).catch(() => {});
  return map;
}

async function getOcMap() {
  if (ocMap) return ocMap;
  if (ocInFlight) return ocInFlight;

  ocInFlight = (async () => {
    staleInFlightFlag.oc = true;
    try {
      const cached = await idbCache.get(IDB_KEYS.OC);
      if (cached && Array.isArray(cached.records)) {
        ocMap = new Map(cached.records.map((r) => [r.canonical_id, r]));
        return ocMap;
      }
      return await loadOcFromNetwork();
    } finally {
      staleInFlightFlag.oc = false;
      ocInFlight = null;
    }
  })();

  return ocInFlight;
}

export async function getProblemDetail(canonicalId) {
  if (detailCache.has(canonicalId)) return detailCache.get(canonicalId);

  const problems = await getProblems();
  const problem = problems.find((p) => p.canonical_id === canonicalId);
  if (!problem) return null;

  // CP/Codeforces pass-through problems never have an oc.json entry —
  // the record from problems.json already has everything the detail page
  // needs. Never fetch the 66MB oc.json for these.
  if (problem.should_generate === false) {
    detailCache.set(canonicalId, problem);
    return problem;
  }

  const oc = await getOcMap();
  const ocRecord = oc.get(canonicalId);
  if (!ocRecord) {
    console.warn(`[dataClient] should_generate:true problem "${canonicalId}" has no matching oc.json record`);
  }

  const merged = mergeOcRecord(problem, ocRecord);
  detailCache.set(canonicalId, merged);
  return merged;
}

// ---- notes ------------------------------------------------------------------

const LEVEL_NAMES = {
  0: 'Foundations', 1: 'Arrays & Strings', 2: 'Core Data Structures',
  3: 'Recursion & Sorting', 4: 'Trees', 5: 'Graphs',
  6: 'Dynamic Programming', 7: 'Advanced', 8: 'Others',
};

export async function getNotesIndex() {
  if (notesIndexCache) return notesIndexCache;

  const topics = NOTES_TOPICS_INDEX.map((t) => ({
    ...t,
    levelName: LEVEL_NAMES[t.level] || 'Other',
    available: AVAILABLE_NOTE_SLUGS.has(t.slug),
  }));

  const byLevel = {};
  for (const t of topics) {
    if (!byLevel[t.level]) byLevel[t.level] = { level: t.level, name: LEVEL_NAMES[t.level], topics: [] };
    byLevel[t.level].topics.push(t);
  }

  notesIndexCache = {
    levels: Object.values(byLevel).sort((a, b) => a.level - b.level),
    total: topics.length,
    ready: topics.filter((t) => t.available).length,
  };
  return notesIndexCache;
}

export async function getNote(slug) {
  const safe = String(slug || '').replace(/[^a-z0-9-]/g, '');
  if (!safe) return null;

  if (noteCache.has(safe)) return noteCache.get(safe);
  if (noteInFlight.has(safe)) return noteInFlight.get(safe);

  const meta = NOTES_TOPICS_INDEX.find((t) => t.slug === safe);
  if (!meta) return null;

  const promise = (async () => {
    try {
      const res = await fetch(`${PATHS.NOTES_DIR}/${safe}.json`);
      if (!res.ok) return null;
      const note = await res.json();
      noteCache.set(safe, note);
      return note;
    } catch (err) {
      console.warn(`[dataClient] failed to load note "${safe}"`, err);
      return null;
    } finally {
      noteInFlight.delete(safe);
    }
  })();

  noteInFlight.set(safe, promise);
  return promise;
}

// Exposed for tests / debugging only — not part of the intended public API.
export const __internal = { PATHS, IDB_KEYS };
