export const NOTES_TOPICS_INDEX = [
  { slug: 'time-space-complexity',             topic: "Time & Space Complexity",                              level: 0 },
  { slug: 'basic-math',                        topic: "Basic Math for CP",                                    level: 0 },
  { slug: 'loops-patterns',                    topic: "Loops & Patterns",                                     level: 0 },
  { slug: '1d-arrays',                         topic: "1D Arrays",                                            level: 1 },
  { slug: '2d-arrays-matrix',                  topic: "2D Arrays / Matrix",                                   level: 1 },
  { slug: 'string-manipulation',               topic: "String Manipulation",                                  level: 1 },
  { slug: 'prefix-sum',                        topic: "Prefix Sum",                                           level: 1 },
  { slug: 'simulation',                        topic: "Simulation",                                           level: 1 },
  { slug: 'two-pointers',                      topic: "Two Pointers",                                         level: 2 },
  { slug: 'sliding-window',                    topic: "Sliding Window",                                       level: 2 },
  { slug: 'hashing',                           topic: "Hashing",                                              level: 2 },
  { slug: 'kadane-algorithm',                  topic: "Kadane's Algorithm",                                   level: 2 },
  { slug: 'stacks',                            topic: "Stacks",                                               level: 3 },
  { slug: 'queues',                            topic: "Queues",                                               level: 3 },
  { slug: 'monotonic-stack',                   topic: "Monotonic Stack",                                      level: 3 },
  { slug: 'monotonic-queue',                   topic: "Monotonic Queue",                                      level: 3 },
  { slug: 'linked-lists',                      topic: "Linked Lists",                                         level: 3 },
  { slug: 'fast-slow-pointers',                topic: "Fast & Slow Pointers",                                 level: 3 },
  { slug: 'recursion-basics',                  topic: "Recursion Basics",                                     level: 4 },
  { slug: 'binary-search',                     topic: "Binary Search",                                        level: 4 },
  { slug: 'binary-search-on-answer',           topic: "Binary Search on Answer",                              level: 4 },
  { slug: 'sorting-algorithms',                topic: "Sorting Algorithms",                                   level: 4 },
  { slug: 'greedy-algorithms',                 topic: "Greedy Algorithms",                                    level: 4 },
  { slug: 'merge-intervals',                   topic: "Merge Intervals",                                      level: 4 },
  { slug: 'backtracking',                      topic: "Backtracking",                                         level: 4 },
  { slug: 'binary-trees',                      topic: "Binary Trees",                                         level: 5 },
  { slug: 'bst',                               topic: "BST",                                                  level: 5 },
  { slug: 'heaps-priority-queue',              topic: "Heaps / Priority Queue",                               level: 5 },
  { slug: 'tries',                             topic: "Tries",                                                level: 5 },
  { slug: 'bfs-dfs',                           topic: "BFS / DFS",                                            level: 6 },
  { slug: 'topological-sort',                  topic: "Topological Sort",                                     level: 6 },
  { slug: 'union-find-dsu',                    topic: "Union Find / DSU",                                     level: 6 },
  { slug: 'mst',                               topic: "MST - Minimum Spanning Tree",                          level: 6 },
  { slug: 'shortest-paths',                    topic: "Shortest Paths (Dijkstra, Bellman-Ford)",              level: 6 },
  { slug: 'bit-manipulation',                  topic: "Bit Manipulation",                                     level: 6 },
  { slug: '1d-dp',                             topic: "1D Dynamic Programming",                               level: 7 },
  { slug: '2d-dp',                             topic: "2D Dynamic Programming",                               level: 7 },
  { slug: 'interval-dp',                       topic: "Interval DP",                                          level: 7 },
  { slug: 'bitmask-dp',                        topic: "Bitmask DP",                                           level: 7 },
  { slug: 'dp-on-graphs',                      topic: "DP on Graphs",                                         level: 7 },
  { slug: 'dp-on-trees',                       topic: "DP on Trees",                                          level: 7 },
  { slug: 'longest-increasing-subsequence',    topic: "Longest Increasing Subsequence",                       level: 7 },
  { slug: 'advanced-graph',                    topic: "Advanced Graph - Bridges, Articulation Points, SCC",   level: 8 },
  { slug: 'segment-trees',                     topic: "Segment Trees",                                        level: 8 },
  { slug: 'fenwick-tree-bit',                  topic: "Fenwick Tree / BIT",                                   level: 8 },
  { slug: 'lca-binary-lifting',                topic: "LCA & Binary Lifting",                                 level: 8 },
  { slug: 'mos-algorithm',                     topic: "Mo's Algorithm",                                       level: 8 },
  { slug: 'eulerian-path',                     topic: "Eulerian Path & Circuit",                              level: 8 },
  { slug: 'string-pattern-matching',           topic: "String Pattern Matching",                              level: 8 },
  { slug: 'number-theory',                     topic: "Number Theory",                                        level: 9 },
  { slug: 'combinatorics',                     topic: "Combinatorics",                                        level: 9 },
  { slug: 'geometry',                          topic: "Geometry Basics",                                      level: 9 },
  { slug: 'divide-conquer',                    topic: "Divide and Conquer",                                   level: 9 },
  { slug: 'sparse-table',                      topic: "Sparse Table",                                         level: 9 },
  { slug: 'math-cp',                           topic: "Math for CP",                                          level: 9 },
  { slug: 'matrix',                            topic: "Matrix Operations",                                    level: 9 },
  { slug: 'sqrt-decomposition',                topic: "Sqrt Decomposition",                                   level: 9 },
  { slug: 'string-algorithms-part-2',          topic: "String Algorithms Part 2",                             level: 9 },
  { slug: 'misc-advanced-techniques',          topic: "Misc Advanced Techniques",                             level: 9 },
  { slug: 'search-and-number-theory-extras',   topic: "Search & Number Theory Extras",                        level: 9 },
  { slug: 'bipartite-matching-max-flow',       topic: "Bipartite Matching & Max Flow",                        level: 9 },
  { slug: 'game-theory',                       topic: "Game Theory",                                          level: 9 },
  { slug: 'design-problems',                   topic: "Design Problems",                                      level: 9 },
  { slug: 'javascript-for-dsa',                topic: "JavaScript for DSA",                                   level: 9 },
];
