export const DSA_TOPICS = [
  'Array',
  'String',
  'Hash Table',
  'Dynamic Programming',
  'Math',
  'Sorting',
  'Greedy',
  'Depth-First Search',
  'Breadth-First Search',
  'Binary Search',
  'Tree',
  'Binary Tree',
  'Linked List',
  'Stack',
  'Two Pointer',
  'Sliding Window',
  'Backtracking',
  'Bit Manipulation',
  'Trie',
  'Recursion',
  'Prefix Sum',
  'Monotonic Stack',
  'Topological Sort',
  'Segment Tree',
  'Divide and Conquer',
  'Number Theory',
  'Combinatorics',
  'Geometry',
  'Simulation',
  'Implementation',
  'Hashing',
  'Shortest Paths',
  'Suffix Array',
];

export const PROBLEM_PATTERNS = [
  'Two Pointer',
  'Sliding Window',
  'Prefix Sum',
  'Binary Search',
  'BFS',
  'DFS',
  'BFS on Trees',
  'DFS on Trees',
  'Dynamic Programming',
  'String DP',
  'DP on Trees',
  'Bitmask DP',
  'Backtracking',
  'Greedy',
  'Hashing',
  'Divide and Conquer',
  'Topological Sort',
  'Bit Manipulation',
  'Monotonic Stack',
  'Segment Tree',
  'Fenwick Tree',
  'Trie',
  'Heap / Priority Queue',
  'Linked List',
  'Stack',
  'Queue',
  'String Manipulation',
  'Recursion',
  'Simulation',
  'Number Theory',
  'Math',
  'Geometry',
  'Combinatorics',
];

export const TOP_COMPANIES = [
  'Google', 'Amazon', 'Microsoft', 'Apple', 'Meta', 'Netflix',
  'Adobe', 'Uber', 'Salesforce', 'Goldman Sachs', 'Bloomberg',
  'LinkedIn', 'Twitter', 'Airbnb', 'ByteDance', 'TCS', 'Infosys',
  'Wipro', 'Flipkart', 'Paytm',
];

export const PLATFORMS = [
  'leetcode', 'codeforces', 'codechef', 'hackerrank', 'atcoder', 'cses', 'geeksforgeeks',
];

export const SORT_OPTIONS = [
  { value: 'frequency',       label: 'Most Popular' },
  { value: 'difficulty_asc',  label: 'Difficulty ↑' },
  { value: 'difficulty_desc', label: 'Difficulty ↓' },
  { value: 'title_asc',       label: 'A → Z' },
];
